#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import os
import sys

# -- General configuration ------------------------------------------------

extensions = [
]

import warnings

sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/../../'))
extensions = ['sphinxcontrib.verilogdomain']

verilog_domain_debug = [
    # "add_debug_content",
    # "print_parser_tree",
    # "print_add_target",
    # "print_objects_tree",
]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# Optional extensions, used only for compatibility checks
_optional_extensions = [
    # (extension_name, extension_test_document)
    ("symbolator_sphinx", "symbolator.rst")
]
import importlib
for ext,docname in _optional_extensions:
    spec = importlib.util.find_spec(ext)
    if not spec:
        exclude_patterns.append(docname)
    else:
        extensions.append(ext)


# Symbiflow theme
html_theme = 'sphinx_symbiflow_theme'
html_theme_options = {
    'header_links' : [
        ('Home', 'index', False, 'home'),
    ],
    # Customize css colors.
    # For details see link.
    # https://getmdl.io/customize/index.html
    #
    # Values: amber, blue, brown, cyan deep_orange, deep_purple, green, grey, indigo, light_blue,
    #         light_green, lime, orange, pink, purple, red, teal, yellow(Default: indigo)
    'primary_color': 'red',
    # Values: Same as primary_color. (Default: pink)
    'accent_color': 'blue',

    # Customize layout.
    # For details see link.
    # https://getmdl.io/components/index.html#layout-section
    'fixed_drawer': True,
    'fixed_header': True,
    'header_waterfall': True,
    'header_scroll': False,

    # Render title in header.
    # Values: True, False (Default: False)
    'show_header_title': False,
    # Render title in drawer.
    # Values: True, False (Default: True)
    'show_drawer_title': True,
    # Render footer.
    # Values: True, False (Default: True)
    'show_footer': True
}

source_suffix = '.rst'

master_doc = 'index'

# General information about the project.
project = 'sphinx-verilog-domain'
copyright = '2018, Various'
author = 'Various'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

html_js_files = [
    'http://livejs.com/live.js'
]

